//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility_Video_Link
    {
        public int Video_Link_Code { get; set; }
        public int Facility_Code { get; set; }
        public string Video_Link { get; set; }
    
        public virtual Gym_Facility Gym_Facility { get; set; }
    }
}
