//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer_Facility_Recommendation
    {
        public int Facility_Recommendation_Code_For_Trainee { get; set; }
        public string Trainer_Id { get; set; }
        public int Facility_Code { get; set; }
        public int Amount_Of_Personal_Repetitions { get; set; }
        public string Amount_Of_Recommended_Repetitions { get; set; }
        public string Recommended_Weight_To_Lift { get; set; }
        public int Personal_Weight_To_Lift { get; set; }
        public string Days_to_Train { get; set; }
        public string Trainee_Id { get; set; }
        public System.DateTime Creation_Date { get; set; }
    
        public virtual Gym_Facility Gym_Facility { get; set; }
        public virtual Trainee Trainee { get; set; }
        public virtual Trainer Trainer { get; set; }
    }
}
