//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee_Facilities_History
    {
        public int Trainee_Facilities_History_Code { get; set; }
        public string Trainee_Id { get; set; }
        public int Amount_Of_Personal_Repetitions { get; set; }
        public int Personal_Weight_To_Lift { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public int Facility_Code { get; set; }
    
        public virtual Trainee Trainee { get; set; }
    }
}
