//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trainee()
        {
            this.Trainer_Facility_Recommendation = new HashSet<Trainer_Facility_Recommendation>();
            this.Trainee_Facilities_History = new HashSet<Trainee_Facilities_History>();
        }
    
        public string Trainee_Id { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string User_Name { get; set; }
        public string Password { get; set; }
        public string Phone_Number { get; set; }
        public System.DateTime Date_Of_Birth { get; set; }
        public double Height { get; set; }
        public double Weight { get; set; }
        public bool Gender { get; set; }
        public string Address { get; set; }
        public int Amount_Of_Training_Per_Week { get; set; }
        public bool Perform_Exercises { get; set; }
        public string Training_Goal { get; set; }
        public int Fitness_Level { get; set; }
        public string Body_Problem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trainer_Facility_Recommendation> Trainer_Facility_Recommendation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Trainee_Facilities_History> Trainee_Facilities_History { get; set; }
    }
}
